### ISSUE TITLE
Article named 'print' triggers printing dialog

### ISSUE THREAD

**Issue by frewsxcv** [rust-lang-nursery/mdBook#258]
https://doc.rust-lang.org/nightly/unstable-book/library-features/print.html

**Comment by Michael-F-Bryan** [comment]
I just tried this locally and it appears the bug is still present. The reason we have this issue is the print page (accessible by the printer icon in the top right) is written to `/print.html`. So when you have an entry in your `SUMMARY.md` file which looks like `[Print](./print.md)` it'll be later clobbered by the print page (chapters are rendered before the print page).

I think the best solution would be to emit an error when someone tries to have a `print.md` file in the root of their `src/` directory. This is a HTML renderer-specific issue, so I think the best way to deal with it would be when chapters are rendered. You'd insert a check to emit an error when the output file's name is `print.html`.

**Comment by notriddle** [comment]
Or name the print-dialog page `_print.html`, and emit an error whenever someone tries to have a markdown file that starts with `_`. That way new internal-files can be added at any time without breaking things.
