### ISSUE TITLE
Partial include should show full file instead of stub when showing hidden lines.

### ISSUE THREAD

**Issue by shingtaklam1324** [rust-lang-nursery/mdBook#618]
Currently, when parts of the code is included, the default stub is included.

**Comment by Michael-F-Bryan** [comment]
Would you be able to show us an example of what you see versus what you expected to happen?

**Comment by carols10cents** [comment]
Ok I think I understand this one because I think I'm having the same issue.

When I have an external file that, say, looks like this:

```
struct User {
    username: String,
    email: String,
    sign_in_count: u64,
    active: bool,
}

fn main() {
    let user1 = User {
        email: String::from("someone@example.com"),
        username: String::from("someusername123"),
        active: true,
        sign_in_count: 1,
    };
}
```

And I include part of the file like this:

``````
```rust
{{#include ../examples/ch05-using-structs-to-structure-related-data/listing-05-02/src/main.rs:9:14}}
```
``````

I correctly see the part of the file rendered:

<img width="764" alt="Screen Shot 2019-04-28 at 3 36 15 PM" src="https://user-images.githubusercontent.com/193874/56869198-709b1500-69cb-11e9-9c71-ef5afa16853e.png">

But when I click the "show hidden lines" link, I see this:

<img width="769" alt="Screen Shot 2019-04-28 at 3 37 32 PM" src="https://user-images.githubusercontent.com/193874/56869215-9b856900-69cb-11e9-989f-9933f5dd610e.png">

The example has been wrapped in `main` and the `allow(unused_variables)` has been added. I think that's what @shingtaklam1324 means by "default stub".

What would be nice is if clicking the "show hidden lines" link expanded to show the rest of the file instead, and only wrapping in `main` if the rest of the file didn't have `main`.

I'm working on extracting TRPL's examples into external files, and this would be really nice to have. I'll probably give this a try soon.
