### ISSUE TITLE
I would like to help out

### ISSUE THREAD

**Issue by dvberkel** [rust-lang-nursery/mdBook#623]
I like Rust and the Rust community. I would love to give back even though I don't have a ton of time on my hands. Since I use mdBook in some of my projects, and seeing the recent project maintenance discussion (#482), I figured that I help out here.

Is this something you would be interested in?

**Comment by Michael-F-Bryan** [comment]
> Is this something you would be interested in?

Most definitely! We love it when new people join and help out :smiley: 

The easiest way to help out is to skim through the bug tracker and see if anything catches your interest. It's always a bit daunting when you encounter a codebase for the first time, so we can help mentor you and point you in the right direction.

Is there any area in particular that you are interested in? I notice you created #622 asking about preprocessors and configuration, so that may be a good place to start (e.g. you could write a small mathjax preprocessor). 

Otherwise I know @sorin-davidoi has done a lot of work on the front-end, so he may have a couple ideas for entry-level/medium-sized projects.

**Comment by dvberkel** [comment]
@Michael-F-Bryan Great.

The mathjax preprocessor sounds interesting. What would that entail? Is there an issue open?

I saw that there are a few open pull-request ready to merge, were it not for the divergence of master and the pull-request branch. I was thinking maybe trying to merge them while retaining original author in the merged commits.

**Comment by mattico** [comment]
It might be helpful to tag some issues as `E-help-needed`. (I wish GitHub had more granular permissions so the tagging and triage work could be spread out more)

**Comment by dvberkel** [comment]
> The mathjax preprocessor sounds interesting. What would that entail? Is there an issue open?

Found it #400. I am going to work on that issue.
