### ISSUE TITLE
Add option to specify where to load a book from

### ISSUE THREAD

**Issue by mdenchev** [rust-lang-nursery/mdBook#655]
I would like to make an online editing interface and it seems like it would be useful to be able to load chapters from a db for example. Is this too far off from what this project is aiming to achieve? I am thinking maybe adding a book loader trait that can default to the current loading from disk but also optionally can be specified when mdBook is used as a library.

Would something like that make sense and would a PR be appreciated for such a feature?

**Comment by Michael-F-Bryan** [comment]
At the moment most of `mdbook` is designed with loading from the file system in mind, although there's no reason why you can't generate a [`Book`] entirely in memory via `Book::new()` and then manually appending `BookItem`s to `my_book.sections`. 

I believe the HTML renderer is hard-coded to render to files on disk, but it's really easy to create something implementing the [`Renderer`] trait.

You're more than welcome to give it a go by using `mdbook` as a library, although things may be a little annoying because most of the crate/application is designed with the filesystem in mind.

[`Book`]: http://rust-lang-nursery.github.io/mdBook/mdbook/book/struct.Book.html
[`Renderer`]: http://rust-lang-nursery.github.io/mdBook/mdbook/renderer/trait.Renderer.html

**Comment by mdenchev** [comment]
Thanks will give that approach a try.
