### ISSUE TITLE
Serve rebuilds for every file individually when a lot of files change

### ISSUE THREAD

**Issue by azerupi** [rust-lang-nursery/mdBook#679]
When a lot of source files change and we were running `mdbook serve`, it will rebuild the book for each file that changed. This is particularly painful when using git and changing branches. During those rebuilds, the served book is broken.

Simply quitting `mdbook` and relaunching the command solves the problem, but it is an annoying paper-cut.

**Comment by Michael-F-Bryan** [comment]
I just noticed this myself when I added a "todo: write this" note to all the unwritten chapters in something I'm working on. It's a real pain when the `mdbook watch`/`mdbook serve` tries to rebuild for every updated file when really it should only do the update once.

The actual culprit is our [`trigger_on_change()`] function in `src/bin/watch.rs` because it'll re-run the function for every change notification, but I'm not 100% sure how we can deal with that. We'd need some sort of "debounce" mechanism to collate a bunch of notifications arriving at the same time into a single "stuff changed" message.

What are your thoughts on something like this?

```
loop {
  let _ = rx.recv();  // block until the first change comes in
  sleep(50ms);  
  let _ = rx.try_iter().count(); // collect all other notifications received while sleeping
  rebuild();
  }
}
```

[`trigger_on_change()`]: https://github.com/rust-lang-nursery/mdBook/blob/69599646e729bab98a11171b86c6fddb13597ae7/src/bin/watch.rs#L78-L85

**Comment by azerupi** [comment]
That could work. Notify seems to send an event for every file changed, even within the 1 second debounce time we give it. So flushing the iterator should do the trick. However, we should decently document/comment this portion of code because it is not obvious what it does. 😉 

I also think that `last()` could be used instead of `count` on the iterator if we do not use the number of changes detected in logs or other things. Both consume the iterator, so I think it should work the same but I find `last()` more obvious in its intent.

**Comment by Michael-F-Bryan** [comment]
> Both consume the iterator, so I think it should work the same but I find last() more obvious in its intent.

Agreed. Although it could also be turned into some sort of `collect()` so we can log *which* files were updated and how... Or is that overkill?

**Comment by azerupi** [comment]
Yes, absolutely! It comes down to what you want to log.
