### ISSUE TITLE
additional css links are not relativized correctly to pages in dirs

### ISSUE THREAD

**Issue by warpfork** [rust-lang-nursery/mdBook#800]
If using `output.html.additional-css`, the filename given will be included at the top of all files... including, unmodified, in files in deeper directories.

This means `additional-css` pretty much presently doesn't work for mdbooks that use directories.  :(

### Workarounds

None that I've discovered.

I considered a workaround of setting `additional-css = ["custom.css", "../custom.css"]`, but this is (sensibly enough) rejected during `mdbook` build because the latter file doesn't exist.

I considered a workaround of making a symlink back up to my custom css file in each dir I have, but it doesn't get copied into the site build dir, so this also doesn't work.

### related

https://github.com/rust-lang-nursery/mdBook/issues/789 is probably related.

**Comment by wirelyre** [comment]
If I'm reading this right, I think this is fixed in #777. (I had the same problem.) The fix should appear in the next release.

In the meantime, you can copy [this file](https://github.com/rust-lang-nursery/mdBook/blob/0c926b3e885679ec81584bfa9fd50cabc103f9f2/src/theme/index.hbs) into `theme/index.hbs` in the root directory, the same one containing `src`. You might have to `mkdir theme` first.

**Comment by ehuss** [comment]
Closing as fixed.
