### ISSUE TITLE
Request: Set default theme from built-in themes

### ISSUE THREAD

**Issue by Phrohdoh** [rust-lang-nursery/mdBook#922]
I'd like to be able to set the default theme to one of the 'built-in' themes _without_ duplicating the files into my source tree.

I imagine a property like `default-theme = "navy"` in `book.toml` under the `book` table.

**Comment by mrec** [comment]
I've wanted this too. Not sure how it would interact with hypothetical support for [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) if and when that becomes widely available, though. Maybe allow `default-theme-light` and `default-theme-dark`?

**Comment by zzy** [comment]
[output.html]
theme = "src/theme"
default-theme = "rust"

**Comment by Phrohdoh** [comment]
```toml
theme = "src/theme"
```

That appears to violate the _without duplicating the files into my source tree_ part of the OP, if I am not mistaken.

**Comment by mrec** [comment]
It looks like the [rust-lang-nursery.github.io copy](https://rust-lang-nursery.github.io/mdBook/format/config.html) of the user guide (linked from this project's README) is lagging behind [latest](https://github.com/rust-lang-nursery/mdBook/blob/master/book-example/src/format/config.md#html-renderer-options). 

Also, the latest doc mentions the `default-theme` option but doesn't include it in the *"This shows **all** available HTML output options in the book.toml"* code sample (my emphasis). Conversely, that sample shows a `searcher` option which isn't otherwise described.
